'use client';
import dynamic from 'next/dynamic';
import {useEffect,useRef,useState} from 'react';
import {languages,labels,filenames,templates,MAX_SOURCE,type LabLanguage,type LabFile,type LabAccess,type LabQuestion,type QuizResult,type RunResult} from '@/lib/aprajita/contract';
import {previewDocument} from '@/lib/aprajita/preview';
const Editor=dynamic(()=>import('./editor'),{ssr:false,loading:()=> <p role="status">Loading editor…</p>});
async function request(path:string,data?:unknown,signal?:AbortSignal){const response=await fetch(`/api/aprajita${path}`,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined,signal});const value=await response.json();if(!response.ok)throw new Error(value.error||'Please try again.');return value;}
export default function Lab({signedIn,onProfile,onSignIn}:{signedIn:boolean;onProfile:()=>void;onSignIn:()=>void}){
 const [access,setAccess]=useState<LabAccess|null>(null),[questions,setQuestions]=useState<LabQuestion[]>([]),[refresher,setRefresher]=useState(''),[configured,setConfigured]=useState(false),[files,setFiles]=useState<LabFile[]>([]);
 const [language,setLanguage]=useState<LabLanguage>('python'),[name,setName]=useState(filenames.python),[source,setSource]=useState(templates.python),[baseline,setBaseline]=useState({source:templates.python,name:filenames.python}),[stdin,setStdin]=useState('');
 const [answers,setAnswers]=useState<Record<string,string>>({}),[quiz,setQuiz]=useState<QuizResult|null>(null),[output,setOutput]=useState<RunResult|null>(null),[preview,setPreview]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const alive=useRef(true);const dirty=source!==baseline.source||name!==baseline.name;
 function select(lang:LabLanguage,text:string,fileName:string){setLanguage(lang);setSource(text);setName(fileName);setBaseline({source:text,name:fileName});setOutput(null);setPreview('');setStdin('');}
 async function load(signal?:AbortSignal){const status=await request('',undefined,signal);if(!alive.current)return;setAccess(status.access);setQuestions(status.questions||[]);setRefresher(status.refresher||'');setConfigured(status.executionConfigured);if(status.access.ready){const saved=await request('/files',undefined,signal);if(!alive.current)return;setFiles(saved.files);if(saved.files.length){const file=saved.files[0];select(file.language,file.source,file.name);}}}
 useEffect(()=>{alive.current=true;const controller=new AbortController();if(signedIn)void load(controller.signal).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});else setLoading(false);return()=>{alive.current=false;controller.abort();};},[signedIn]);
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};const leave=(event:Event)=>{if(dirty&&!confirm('Leave without saving your code?'))event.preventDefault();};window.addEventListener('aprajita:leave',leave);window.addEventListener('beforeunload',warn);return()=>{window.removeEventListener('aprajita:leave',leave);window.removeEventListener('beforeunload',warn);};},[dirty]);
 async function action(work:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await work();}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Please try again.');}finally{if(alive.current)setBusy(false);}}
 const discard=()=>!dirty||confirm('Discard unsaved changes? Save first to keep your work.');
 const heading=<div className="page-heading"><div><span className="eyebrow">A LITTLE PRACTICE, EVERY DAY</span><h1>APRAJITA <em>Code Lab.</em></h1><p>Write, try and save your own programs.</p></div></div>;
 if(!signedIn)return <section className="aprajita enter">{heading}<div className="panel"><h2>Sign in to open your lab</h2><p>Your saved education profile determines access. Your files stay with your account.</p><button className="primary" onClick={onSignIn}>Sign in</button></div></section>;
 if(loading)return <section className="aprajita">{heading}<p role="status">Checking your saved profile…</p></section>;
 return <section className="aprajita enter">{heading}{error&&<p className="notice error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 {!access?.eligible?<div className="panel"><h2>{access?.needsProfile?'Complete your education profile':'Code Lab access'}</h2><p>{access?.reason||'Access could not be checked. Please reload and try again.'}</p><p>B.Tech/B.E. students in all branches qualify. Students in Classes 8–12 need an actual computing subject in their saved profile; stream alone does not qualify.</p><button className="primary" onClick={onProfile}>Update profile</button></div>:!access.ready?<div className="panel lab-assessment"><h2>A quick readiness check</h2><p>Answer all five questions. Get at least three right to open the lab. You can retry as often as you need.</p><details><summary>Short refresher</summary><p>{refresher}</p></details><form onSubmit={event=>{event.preventDefault();void action(async()=>{const result=await request('/readiness',{version:access.version,answers:questions.map(q=>answers[q.id])});if(!alive.current)return;setQuiz(result);if(result.passed)await load();});}}>{questions.map((question,index)=><fieldset key={question.id}><legend>{index+1}. {question.prompt}</legend>{question.options.map(option=><label key={option.id}><input type="radio" name={question.id} required value={option.id} checked={answers[question.id]===option.id} onChange={()=>setAnswers({...answers,[question.id]:option.id})}/>{option.text}</label>)}</fieldset>)}<button className="primary" disabled={busy}>{busy?'Checking…':'Check answers'}</button></form></div>:<>
 <div className="lab-toolbar"><label>Language<select value={language} disabled={busy} onChange={event=>{if(discard()){const lang=event.target.value as LabLanguage;const saved=files.find(f=>f.language===lang);select(lang,saved?.source??templates[lang],saved?.name??filenames[lang]);}}}>{languages.map(lang=><option value={lang} key={lang}>{labels[lang]}</option>)}</select></label><label>Saved files<select value="" disabled={busy} onChange={event=>{const file=files.find(f=>f.id===event.target.value);if(file&&discard())select(file.language,file.source,file.name);}}><option value="">Open a saved file…</option>{files.map(file=><option key={file.id} value={file.id}>{labels[file.language]} · {file.name}</option>)}</select></label><label>File name<input value={name} maxLength={80} onChange={event=>setName(event.target.value)}/></label></div>
 <div className="lab-editor-shell"><Editor language={language} value={source} onChange={setSource}/></div><div className="lab-actions"><button className="primary" disabled={busy||source.length>MAX_SOURCE} onClick={()=>void action(async()=>{if(language==='html'){setPreview(previewDocument(source));setOutput(null);return;}const result=await request('/run',{language,source,stdin});if(alive.current)setOutput(result);})}>{language==='html'?'Preview':busy?'Please wait…':'Run'}</button><button className="secondary" disabled={busy||source.length>MAX_SOURCE} onClick={()=>void action(async()=>{const result=await request('/files',{language,name,source});if(!alive.current)return;setFiles(previous=>[result.file,...previous.filter(f=>f.id!==result.file.id)]);setBaseline({name,source});setNotice('Saved to your account.');})}>Save</button><button className="text-button" disabled={busy} onClick={()=>{if(discard())select(language,templates[language],filenames[language]);}}>Reset to starter</button><span className="muted">{dirty?'Unsaved changes':'Ready'} · {source.length}/{MAX_SOURCE} characters</span></div>
 {language!=='html'&&<><label className="field"><span>Program input (optional)</span><textarea value={stdin} maxLength={1000} rows={2} onChange={event=>setStdin(event.target.value)} placeholder="Input passed to your program"/></label>{!configured&&<p className="inline-note">Program execution is not configured yet. Editing and saving are available. Ask the platform team to connect the isolated runner.</p>}<p className="muted">Runs use an isolated service with time, memory and output limits. Do not put passwords or personal information in your code.</p></>}
 {language==='html'&&<p className="muted">Preview is isolated from VIKAS storage. Scripts, forms, external links and network access are disabled. HTML and inline CSS are supported.</p>}
 <section className="lab-output" aria-label="Program output" aria-live="polite"><h2>{language==='html'?'Preview':'Output & errors'}</h2>{language==='html'?preview?<iframe title="Isolated HTML preview" sandbox="" referrerPolicy="no-referrer" srcDoc={preview}/>:<p>Choose Preview to view your page.</p>:output?<><p>{output.status}{output.truncated?' · Output limit reached':''}</p><pre>{output.output||'(No standard output)'}</pre>{output.error&&<pre className="lab-error">{output.error}</pre>}</>:<p>Run your program to see its output here.</p>}</section></>}
 {quiz&&<div className="panel lab-review"><h2>{quiz.passed?'Ready to practise':'Keep practising'} · {quiz.score}/5</h2>{quiz.results.map((result,index)=><p key={result.id}><strong>{index+1}. {result.correct?'Correct':'Review this answer'}</strong> {result.explanation}</p>)}{!quiz.passed&&<button className="secondary" onClick={()=>{setAnswers({});setQuiz(null);}}>Try again</button>}</div>}
 </section>;
}
