'use client';
import {useState} from 'react';
import type {Chapter} from '@/lib/chapter-catalogue';
import type {Resource} from '@/lib/types';
function Video({resource,onAccepted,onDisha,hasGoal}:{resource:Resource;onAccepted:()=>Promise<void>;onDisha:()=>void;hasGoal:boolean}){
 const [minutes,setMinutes]=useState(20),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function accept(){if(busy)return;setBusy(true);setMessage('');try{const response=await fetch(`/api/resources/${resource._id}/accept`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({minutes})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Please try again.');await onAccepted();setMessage('Saved to your plan. You decide when the step is complete.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <article className="chapter-video"><h4>{resource.title}</h4><p>{resource.video?.channelName||'Channel unknown'} · {resource.video?.language==='unverified'?'Language unverified':resource.video?.language}{resource.video?.durationMinutes!=null?` · ${resource.video.durationMinutes} min`:' · Duration unknown'}</p><details><summary>Source and review limits</summary><p>Research review: {resource.video?.reviewDepth.replaceAll('_',' ')}. {resource.video?.publicationBasis==='operator_requested_no_review'?'Made available at the operator’s request. Links and curriculum mappings have not been independently reviewed.':'Published after an editor approved these chapter mappings.'}</p><p>{resource.video?.reviewLimitations}</p>{resource.video?.channelUrl&&<a href={resource.video.channelUrl} target="_blank" rel="noopener noreferrer">YouTube channel ↗</a>}</details><div className="topic-actions"><a className="secondary" href={resource.url} target="_blank" rel="noopener noreferrer">Open YouTube ↗</a><label className="field"><span>Your session (minutes)</span><input type="number" min={5} max={120} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><button className="primary" disabled={busy||!hasGoal||!Number.isInteger(minutes)||minutes<5||minutes>120} onClick={()=>void accept()}>Add to my plan</button><button className="text-button" onClick={onDisha}>Ask DISHA</button></div>{!hasGoal&&<p>Save a personal goal in your profile to add a session.</p>}<p role="status">{message}</p></article>;
}
export function ChapterResources({chapters,resources,onAccepted,onDisha,hasGoal,query}:{chapters:Chapter[];resources:Resource[];onAccepted:()=>Promise<void>;onDisha:()=>void;hasGoal:boolean;query:string}){
 if(!chapters.length)return null;
 const subjects=[...new Set(chapters.map(c=>c.officialSubjectName))];
 return <section className="chapter-resources" aria-label="Videos by chapter"><p className="inline-note">Chapter order follows the supplied catalogue. Full syllabus and subtopic coverage have not been verified. Opening a video does not complete a task.</p>{subjects.map(subject=><section key={subject} aria-label={subject}><h2>{subject==='English'?'English · Literature':subject}</h2>{chapters.filter(c=>c.officialSubjectName===subject).sort((a,b)=>a.chapterOrder-b.chapterOrder).map(c=>{const videos=resources.filter(r=>r.chapterMappings?.some(m=>m.chapterId===c.chapterId&&m.chapter.textbookEdition===c.textbookEdition&&m.chapter.textbookTitle===c.textbookTitle&&m.chapter.academicSession===c.academicSession)).sort((a,b)=>(a.chapterMappings!.find(m=>m.chapterId===c.chapterId)!.sequencePosition-b.chapterMappings!.find(m=>m.chapterId===c.chapterId)!.sequencePosition)||a.title.localeCompare(b.title));return <section key={`${c.chapterId}|${c.textbookTitle}|${c.textbookEdition}|${c.academicSession}`} className="chapter-section">{(c.unitTitle||c.theme)&&<p className="muted">{c.unitTitle?`Unit ${c.unitOrder}: ${c.unitTitle}`:c.theme}</p>}<h3>{c.chapterOrder}. {c.chapterTitle}</h3><p className="muted">{c.textbookTitle} · Edition {c.textbookEdition} · Session {c.academicSession}</p>{videos.length?videos.map(r=><Video key={r._id} resource={r} hasGoal={hasGoal} onAccepted={onAccepted} onDisha={onDisha}/>):<p>{query?'No approved videos match your search in this chapter.':'No approved, active videos for this chapter yet.'}</p>}</section>;})}</section>)}</section>;
}
