'use client';
import {useEffect,useState} from 'react';
import {stages} from '@/lib/types';
import type {KnowledgeInput} from '@/lib/mentor-contract';
type Entry=KnowledgeInput&{_id:string;version:string;status:string;reviewedAt?:string};
async function api(path='',method='GET',value?:unknown){const r=await fetch(`/api/mentor/knowledge${path}`,{method,headers:value?{'Content-Type':'application/json'}:undefined,body:value?JSON.stringify(value):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error||'Please try again.');return d;}
export function KnowledgeReview(){
 const [entries,setEntries]=useState<Entry[]>([]),[mappings,setMappings]=useState<{topicId:string;title:string;objectives:string[]}[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [sections,setSections]=useState([{heading:'',text:''}]),[prerequisites,setPrerequisites]=useState<KnowledgeInput['prerequisites']>([]);
 async function load(){const r=await api();setEntries(r.knowledge);setMappings(r.assessmentMappings);}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="knowledge-review panel"><h2>DISHA knowledge</h2><p>Only approved text is retrievable. Supply your own writing or content you have permission to use. A resource link alone is not a lesson.</p>{error&&<p role="alert" className="inline-note error">{error}</p>}{notice&&<p role="status">{notice}</p>}
  <details><summary>Add a knowledge version for review</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{await api('','POST',{topicId:f.get('topicId'),title:f.get('title'),subject:f.get('subject'),stage:f.get('stage'),language:f.get('language'),boardMode:f.get('boardMode'),boards:String(f.get('boards')||'').split(',').map(x=>x.trim()).filter(Boolean),sourceUrl:f.get('sourceUrl'),license:f.get('license'),rightsConfirmed:f.get('rights')==='on',sections,prerequisites});setNotice('Draft saved. Read it below before approving.');});}}>
   <label className="field"><span>Topic key</span><input name="topicId" required maxLength={100} pattern="[A-Za-z0-9_-]+"/></label><label className="field"><span>Topic title</span><input name="title" required maxLength={150}/></label><label className="field"><span>Subject</span><input name="subject" required maxLength={100}/></label><label className="field"><span>Education stage</span><select name="stage">{stages.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><label className="field"><span>Language</span><input name="language" required maxLength={40} defaultValue="English"/></label><label className="field"><span>Board applicability</span><select name="boardMode"><option value="general">General content, not tied to a board</option><option value="specific">Only the boards listed below</option></select></label><label className="field"><span>Exact board names, comma separated (specific content only)</span><input name="boards" maxLength={2000}/></label><label className="field"><span>Source URL</span><input name="sourceUrl" type="url" required maxLength={1500}/></label><label className="field"><span>Authorship, permission or license</span><input name="license" required maxLength={300}/></label>
   <h3>Meaningful sections</h3>{sections.map((s,i)=><fieldset key={i}><legend>Section {i+1}</legend><label className="field"><span>Heading</span><input value={s.heading} required maxLength={150} onChange={e=>setSections(sections.map((x,n)=>n===i?{...x,heading:e.target.value}:x))}/></label><label className="field"><span>Plain text (no HTML)</span><textarea value={s.text} required maxLength={1800} rows={5} onChange={e=>setSections(sections.map((x,n)=>n===i?{...x,text:e.target.value}:x))}/></label>{sections.length>1&&<button type="button" className="text-button" onClick={()=>setSections(sections.filter((_,n)=>n!==i))}>Remove section</button>}</fieldset>)}{sections.length<6&&<button type="button" className="secondary" onClick={()=>setSections([...sections,{heading:'',text:''}])}>Add section</button>}
   <h3>Prerequisites supported by this source</h3><p>Map concepts to exact assessment objective text below. Unmapped concepts remain not yet checked.</p><details><summary>Available unvalidated assessment mappings</summary>{mappings.map(m=><div key={m.topicId}><strong>{m.title} · {m.topicId}</strong><ul>{m.objectives.map(o=><li key={o}>{o}</li>)}</ul></div>)}</details>
   {prerequisites.map((p,i)=><fieldset key={i}><legend>Prerequisite {i+1}</legend>{(['topicId','title','reason'] as const).map(key=><label className="field" key={key}><span>{key==='topicId'?'Assessment topic key':key==='title'?'Concept name':'Why it matters (from source)'}</span><input required maxLength={key==='reason'?500:key==='title'?150:100} value={p[key]} onChange={e=>setPrerequisites(prerequisites.map((x,n)=>n===i?{...x,[key]:e.target.value}:x))}/></label>)}<label className="field"><span>Exact objective text, one per line</span><textarea required maxLength={4000} value={p.objectives.join('\n')} onChange={e=>setPrerequisites(prerequisites.map((x,n)=>n===i?{...x,objectives:e.target.value.split('\n')}:x))}/></label><label className="field"><span>Evidence freshness window in days</span><input type="number" min={1} max={365} value={p.evidenceMaxAgeDays} onChange={e=>setPrerequisites(prerequisites.map((x,n)=>n===i?{...x,evidenceMaxAgeDays:Number(e.target.value)}:x))}/></label><button type="button" className="text-button" onClick={()=>setPrerequisites(prerequisites.filter((_,n)=>n!==i))}>Remove prerequisite</button></fieldset>)}{prerequisites.length<6&&<button type="button" className="secondary" onClick={()=>setPrerequisites([...prerequisites,{topicId:'',title:'',reason:'',objectives:[],evidenceMaxAgeDays:90}])}>Add prerequisite</button>}
   <label className="check-label"><input name="rights" type="checkbox" required/>I wrote this content or have permission under the stated license to store and use it.</label><button className="primary" disabled={busy}>Save draft for review</button>
  </form></details>
  {!entries.length&&<p>No knowledge has been supplied. DISHA will show an honest knowledge gap.</p>}
  <ul className="mentor-list">{entries.map(e=><li key={e._id}><details><summary>{e.title} · {e.status} · {e.version.slice(0,8)}</summary><p>{e.subject} · {e.stage} · {e.language} · {e.boardMode==='general'?'General content':e.boards.join(', ')}</p><a href={e.sourceUrl} target="_blank" rel="noopener noreferrer">Source ↗</a><p>{e.license}</p>{e.sections.map((s,i)=><div key={i}><h3>{s.heading}</h3><p className="knowledge-text">{s.text}</p></div>)}{e.prerequisites.map(p=><div key={p.topicId}><h3>Prerequisite: {p.title}</h3><p>{p.reason}</p><p>{p.topicId} · {p.evidenceMaxAgeDays} days · {p.objectives.join('; ')}</p></div>)}<div className="topic-actions"><button className="secondary" disabled={busy} onClick={()=>void run(async()=>{await api(`/${e._id}`,'PATCH',{decision:e.status==='approved'?'withdraw':'approve',version:e.version});setNotice(e.status==='approved'?'Content withdrawn from retrieval.':'This exact content version is approved.');})}>{e.status==='approved'?'Withdraw from retrieval':'Approve this version'}</button></div></details></li>)}</ul>
 </section>;
}
