import Link from 'next/link';
import {ArrowRight,Compass,BookOpen,MessageCircle,CornerDownRight} from 'lucide-react';
import {landingAction} from '@/lib/navigation';
export function LandingPage({signedIn,themeControl}:{signedIn:boolean;themeControl:React.ReactNode}){
 const action=landingAction(signedIn);
 return <div className="landing"><a className="skip" href="#main">Skip to content</a>
  <header className="landing-header"><div className="landing-header-inner"><Link href="/" className="brand" aria-label="VIKAS home">VIKAS<span className="brand-divider"/><span className="brand-tag">Room to grow.</span></Link><nav aria-label="Public navigation"><a className="landing-how-link" href="#how-it-works">How it works</a>{themeControl}{!signedIn&&<Link href="/login" className="landing-sign-in">Sign in</Link>}<Link href={action.href} className="primary landing-header-cta">{action.label}</Link></nav></div></header>
  <main id="main" className="landing-main">
   <section className="landing-hero" aria-labelledby="landing-title"><div className="landing-intro landing-reveal"><span className="eyebrow">A LITTLE DIRECTION. AT YOUR PACE.</span><h1 id="landing-title">Your goal.<br/>Your next step.<br/><em>Room to grow.</em></h1><p>Big plans can start small. VIKAS helps you choose a manageable next step, save your progress and come back ready to continue.</p><div className="landing-actions"><Link href={action.href} className="primary">{action.label}<ArrowRight size={18} aria-hidden="true"/></Link><a href="#how-it-works" className="text-button">See how it works</a></div><p className="landing-note">Your direction can change. Your choices stay yours.</p></div>
    <figure className="process-illustration landing-reveal"><div className="process-caption"><span>A small step, then another</span><span aria-hidden="true">↗</span></div><svg className="process-line" viewBox="0 0 400 350" aria-hidden="true" focusable="false"><path d="M 75 60 C 225 0 360 35 335 160 S 95 150 70 245 S 200 335 340 290"/></svg><ol className="process-steps"><li><span className="process-number">01</span><div><strong>Goal</strong><span>Choose your direction</span></div></li><li><span className="process-number">02</span><div><strong>Next step</strong><span>Make it manageable</span></div></li><li><span className="process-number">03</span><div><strong>Reflection</strong><span>Notice what helped</span></div></li><li><span className="process-number">04</span><div><strong>Continue</strong><span>Choose what comes next</span></div></li></ol><figcaption>A simple illustration of the process, not student activity.</figcaption></figure>
   </section>
   <section id="how-it-works" className="landing-benefits" aria-labelledby="benefits-title"><div className="landing-section-heading"><span className="eyebrow">HOW IT WORKS</span><h2 id="benefits-title">A little structure.<br/>Space to make it yours.</h2><p>One place for what you want to learn, what you try and what comes next.</p></div><div className="benefit-list">
    <article><span className="benefit-icon"><Compass size={23} aria-hidden="true"/></span><div><span className="section-label">TODAY</span><h3>One clear next step.</h3><p>Set a goal and choose a step that fits your time. Reflect on how it felt, then accept, edit or leave the next suggestion.</p></div></article>
    <article><span className="benefit-icon"><BookOpen size={23} aria-hidden="true"/></span><div><span className="section-label">MY JOURNEY</span><h3>Your progress has a place.</h3><p>Save your plan and reflections to your account. Return to your next action and keep your own growth journal as you go.</p></div></article>
    <article><span className="benefit-icon"><MessageCircle size={23} aria-hidden="true"/></span><div><span className="section-label">DISHA</span><h3>Guidance. With you in control.</h3><p>DISHA can use saved context and approved knowledge to suggest a next step. When evidence is missing, it says so. AI explanations depend on service availability.</p></div></article>
   </div></section>
   <section className="landing-pathways" aria-labelledby="pathways-title"><div><span className="eyebrow">DIFFERENT STARTING POINTS</span><h2 id="pathways-title">Wherever you are<br/>in your studies.</h2><p>Shape your profile around what you actually study, then build a personal plan.</p></div><div><ul><li><CornerDownRight size={18} aria-hidden="true"/><span>School, Classes 8–10</span></li><li><CornerDownRight size={18} aria-hidden="true"/><span>Senior secondary, Classes 11–12</span></li><li><CornerDownRight size={18} aria-hidden="true"/><span>Diploma, ITI and Polytechnic</span></li><li><CornerDownRight size={18} aria-hidden="true"/><span>Bachelor’s and postgraduate studies</span></li></ul><p className="landing-note">Profile and planning support spans these pathways. Topic checks and resources currently cover selected Class 11 and bachelor’s topics; coverage varies.</p></div></section>
   <section className="landing-final" aria-labelledby="final-title"><span className="eyebrow">START WITH SOMETHING SMALL</span><h2 id="final-title">You don’t need the whole plan.<br/>Just somewhere to begin.</h2><Link href={action.href} className="primary">{action.label}<ArrowRight size={18} aria-hidden="true"/></Link></section>
  </main><footer className="landing-footer"><span><strong>VIKAS</strong> · A little progress, every day.</span><Link href="/privacy">Privacy &amp; information</Link></footer>
 </div>;
}
