'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import type {ChatMessage,Profile} from '@/lib/types';
import type {MentorResponse,StudentContext} from '@/lib/mentor-contract';
import {TopicLearning} from './topic-learning';
async function api(path:string,method='GET',body?:unknown){const r=await fetch(`/api/mentor${path}`,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error||'Please try again.');return d;}
type Memory={_id:string;topicId:string;text:string;source:string;updatedAt:string};
type Message=ChatMessage&{mentor?:MentorResponse};
const evidenceLabel={profile_self_report:'Profile · self-reported',confirmed_self_report:'Confirmed memory · self-reported',assessment:'Unvalidated topic-check evidence',completed_task:'Completed-task record'};
function MentorTurn({item,busy,decide,remember,choose,check}:{item:Message;busy:boolean;decide:(id:string,v:unknown)=>void;remember:(v:unknown)=>void;choose:(choice:'refresher'|'continue',topicId?:string)=>void;check:()=>void}){
 const [editing,setEditing]=useState(false),[dismissed,setDismissed]=useState(false);
 const m=item.mentor;if(!m)return null;
 const proposal=m.proposal;
 return <div className="mentor-result">
  {m.prerequisites.length>0&&<section><h3>Prerequisites to consider</h3>{m.prerequisiteSource&&<a href={m.prerequisiteSource.url} target="_blank" rel="noopener noreferrer">Source: {m.prerequisiteSource.title}</a>}<ul className="mentor-list">{m.prerequisites.map(p=><li key={p.topicId}><strong>{p.title}</strong><span className="pill">{p.status==='supported'?'Some recent evidence':p.status==='revisit'?'Worth revisiting':'Not yet checked'}</span><p>{p.reason}</p><p>{p.explanation}</p></li>)}</ul></section>}
  {m.uncertainty.length>0&&<details><summary>What remains uncertain</summary><ul>{m.uncertainty.map(t=><li key={t}>{t}</li>)}</ul></details>}
  <details><summary>What saved evidence DISHA used</summary>{m.evidence.length?<ul className="mentor-list">{m.evidence.map((e,i)=><li key={`${e.sourceRef}-${i}`}><strong>{evidenceLabel[e.source]}</strong><p>{e.text}</p><small>{e.topicId||'Profile context'} · {e.at?new Date(e.at).toLocaleDateString():'Date not recorded'}{e.version?` · Version ${e.version.slice(0,8)}`:''}</small></li>)}</ul>:<p>No relevant saved evidence was found.</p>}</details>
  {!!m.recentProgress?.length&&<details><summary>Recent progress DISHA considered</summary><ul className="mentor-list">{m.recentProgress.map((p,i)=><li key={i}><strong>{p.title}</strong><p>{p.status==='done'?'Marked complete':p.status==='needs_help'?'Help requested':p.status==='irrelevant'?'No longer relevant':'To do'}{p.feeling?` · ${p.feeling.replaceAll('_',' ')}`:''}</p>{p.reflection&&<p>{p.reflection}</p>}<small>{p.at?new Date(p.at).toLocaleDateString():'Date not recorded'} · Activity does not establish mastery.</small></li>)}</ul></details>}
  {m.passages.length>0&&<details><summary>Sources and retrieved passages</summary><ol>{m.passages.map(p=><li key={p.id}><a href={p.sourceUrl} target="_blank" rel="noopener noreferrer">{p.title} — {p.heading}</a><p>{p.text}</p><small>Version {p.version.slice(0,8)} · Reviewed {new Date(p.reviewedAt).toLocaleDateString()}</small></li>)}</ol></details>}
  {m.resources.length>0&&<div><h3>Reviewed resource links</h3><ul>{m.resources.map(r=><li key={r.id}><a href={r.url} target="_blank" rel="noopener noreferrer">{r.title} ↗</a></li>)}</ul><p>These links are resource metadata, not ingested lessons.</p></div>}
  {m.mode!=='conversation'&&<><div className="topic-actions" aria-label="Choose how to continue"><button className="secondary" disabled={busy} onClick={check}>Quick topic check</button><button className="secondary" disabled={busy} onClick={()=>choose('refresher',m.topic?.id)}>Prerequisite refresher</button><button className="text-button" disabled={busy} onClick={()=>choose('continue',m.topic?.id)}>Continue to the topic</button></div>
  <section className="mentor-proposal"><h3>{proposal.title}</h3><p>{proposal.explanation}</p><p>{proposal.minutes} minutes · {proposal.notes}</p>
   {proposal.status==='pending'?editing?<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);decide(item._id,{decision:'edit',title:f.get('title'),notes:f.get('notes'),minutes:Number(f.get('minutes'))});setEditing(false);}}><label className="field"><span>Step</span><input name="title" defaultValue={proposal.title} required maxLength={150}/></label><label className="field"><span>Notes</span><textarea name="notes" defaultValue={proposal.notes} maxLength={2000}/></label><label className="field"><span>Minutes</span><input name="minutes" type="number" min={5} max={600} required defaultValue={proposal.minutes}/></label><div className="topic-actions"><button className="primary" disabled={busy}>Save edited step to my plan</button><button type="button" className="text-button" onClick={()=>setEditing(false)}>Cancel</button></div></form>:<div className="topic-actions"><button className="primary" disabled={busy} onClick={()=>decide(item._id,{decision:'accept'})}>Accept step</button><button className="secondary" disabled={busy} onClick={()=>setEditing(true)}>Edit first</button><button className="text-button" disabled={busy} onClick={()=>decide(item._id,{decision:'reject'})}>Not now</button></div>:<p role="status">{proposal.status==='accepted'?'Step saved to your plan.':'Suggestion dismissed. You can continue independently.'}</p>}
  </section></>}
  {m.memorySuggestion&&!dismissed&&<details><summary>Optional memory — confirm before saving</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);remember({messageRef:item._id,topicId:m.memorySuggestion!.topicId,text:f.get('text'),confirmed:true});}}><p>This is an interpretation of your message, not a confirmed fact. Edit it or leave it unsaved.</p><label className="field"><span>What would you like DISHA to remember?</span><textarea name="text" defaultValue={m.memorySuggestion.text} maxLength={300} required/></label><div className="topic-actions"><button className="secondary" disabled={busy}>Confirm and remember</button><button type="button" className="text-button" onClick={()=>setDismissed(true)}>Do not save</button></div></form></details>}
 </div>;
}
export function MentorWorkspace({signedIn,profile,messages,geminiConfigured,onReload,onProfile,onSignIn}:{signedIn:boolean;profile:Profile;messages:ChatMessage[];geminiConfigured:boolean;onReload:()=>Promise<void>;onProfile:()=>void;onSignIn:()=>void}){
 const [message,setMessage]=useState(''),[language,setLanguage]=useState('English'),[topicId,setTopic]=useState('');
 const [context,setContext]=useState<StudentContext|null>(null),[topics,setTopics]=useState<{id:string;title:string}[]>([]),[memories,setMemories]=useState<Memory[]>([]),[showMemory,setShowMemory]=useState(false),[editMemory,setEditMemory]=useState<string|null>(null);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[showCheck,setShowCheck]=useState(false);const lock=useRef(false);const checkPanel=useRef<HTMLElement>(null);
 useEffect(()=>{if(showCheck)checkPanel.current?.focus();},[showCheck]);
 async function loadContext(){const r=await api(`/context?language=${encodeURIComponent(language)}`);setContext(r.context);setMemories(r.memories);setTopics(r.topics);}
 useEffect(()=>{let cancelled=false;if(signedIn)api(`/context?language=${encodeURIComponent(language)}`).then(r=>{if(!cancelled){setContext(r.context);setMemories(r.memories);setTopics(r.topics);}}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[signedIn,language]);
 async function run(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);lock.current=false;}}
 async function send(text:string,choice='consider',selected=topicId){if(!signedIn){onSignIn();return;}await run(async()=>{await api('','POST',{message:text,language,choice,...(selected?{topicId:selected}:{})});setMessage('');await onReload();});}
 async function mutate(path:string,method:string,value?:unknown){await run(async()=>{await api(path,method,value);await Promise.all([onReload(),loadContext()]);setNotice('Saved.');});}
 function submit(e:FormEvent){e.preventDefault();void send(message);}
 return <section className="enter"><div className="page-heading"><div><span className="eyebrow">A LITTLE HELP ALONG THE WAY</span><h1>Meet <em>DISHA.</em></h1><p>Talk through your learning question using your saved context. Sources are shown when approved passages are available.</p></div><button className="secondary" aria-expanded={showMemory} onClick={()=>setShowMemory(!showMemory)}>What DISHA remembers</button></div>
  {error&&<p role="alert" className="inline-note error">{error}</p>}{notice&&<p role="status">{notice}</p>}
  {showMemory&&<section className="memory panel mentor-memory"><h2>What DISHA remembers</h2><p>{context?.education||'No saved education details yet.'}</p><p>{context?.goal||'No saved goal yet.'}</p><button className="text-button" onClick={onProfile}>Edit my profile</button><p>Profile entries and confirmed memories are self-reported. Task completion does not prove mastery. Forgetting a memory excludes it from future mentor context; conversation history is cleared separately.</p>
   {!memories.length&&<p>No extra mentor memories have been confirmed.</p>}<ul className="mentor-list">{memories.map(m=><li key={m._id}>{editMemory===m._id?<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate(`/memory/${m._id}`,'PATCH',{text:f.get('text'),confirmed:true});setEditMemory(null);}}><label className="field"><span>Edit memory about {m.topicId}</span><textarea name="text" defaultValue={m.text} maxLength={300} required/></label><button className="secondary" disabled={busy}>Confirm change</button><button type="button" className="text-button" onClick={()=>setEditMemory(null)}>Cancel</button></form>:<><p>{m.text}</p><small>{m.topicId} · {m.source.replaceAll('_',' ')} · {new Date(m.updatedAt).toLocaleDateString()}</small><div className="topic-actions"><button className="text-button" disabled={busy} onClick={()=>setEditMemory(m._id)}>Edit</button><button className="text-button" disabled={busy} onClick={()=>void mutate(`/memory/${m._id}`,'DELETE')}>Forget</button></div></>}</li>)}</ul>
   {signedIn&&<details><summary>Add a memory yourself</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate('/memory','POST',{topicId:f.get('topicId'),text:f.get('text'),confirmed:true});}}><label className="field"><span>Topic</span><select name="topicId" required><option value="general">Study preferences</option>{topics.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label className="field"><span>Your experience or preference</span><textarea name="text" required maxLength={300}/></label><button className="secondary" disabled={busy}>Confirm and remember</button></form></details>}
  </section>}
  <div className="mentor-controls"><label className="field"><span>Topic (optional)</span><select value={topicId} onChange={e=>setTopic(e.target.value)}><option value="">Describe your topic in the message</option>{topics.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label className="field"><span>Language</span><input value={language} maxLength={40} onChange={e=>{setLanguage(e.target.value);setTopic('');}}/></label></div>
  {!geminiConfigured&&<p className="inline-note">AI conversation is not configured yet. You can view your saved context; approved excerpts appear only when matching sources are available.</p>}
  <div className="chat panel">{messages.length?<div className="messages">{(messages as Message[]).map(m=><article className={`message ${m.role}`} key={m._id}><span>{m.role==='user'?'You':'DISHA'}</span><p>{m.content}</p>{m.role==='assistant'&&<MentorTurn item={m} busy={busy} decide={(id,v)=>void mutate(`/proposals/${id}`,'PATCH',v)} remember={v=>void mutate('/memory','POST',v)} choose={(choice,id)=>void send(choice==='continue'?'I want to continue to the topic.':'I would like a prerequisite refresher.',choice,id)} check={()=>setShowCheck(true)}/>}</article>)}</div>:<div className="empty"><h2>What would you like to understand?</h2><p>Ask about a topic. DISHA will show which prerequisites have evidence and what is still uncertain.</p></div>}
   {busy&&<p role="status">Reading the available context…</p>}<form className="chat-compose" onSubmit={submit}><input aria-label="Message DISHA" placeholder="What would you like to learn?" value={message} maxLength={2000} onChange={e=>setMessage(e.target.value)}/><button className="primary" disabled={busy||!message.trim()||!language.trim()}>{signedIn?'Send':'Sign in'}</button></form>
  </div>
  {showCheck&&<section className="panel" ref={checkPanel} tabIndex={-1}><h2>Available topic checks</h2><p>A check may not yet exist for the prerequisite you want. These checks are optional and unvalidated.</p><TopicLearning initialOpen hasGoal={!!profile.goal.trim()} onAccepted={onReload}/><button className="text-button" onClick={()=>setShowCheck(false)}>Close checks</button></section>}
  <div className="chat-foot"><span>Educational explanations can be mistaken. Check their sources.</span>{messages.length>0&&<button className="text-button" disabled={busy} onClick={()=>{if(confirm('Delete your saved conversation? Confirmed mentor memories remain until you forget them.'))void mutate('','DELETE');}}>Clear conversation</button>}</div>
  <p className="muted">When AI is configured, your question, a limited amount of your saved profile, goal and recent progress are shared with Google to write a reply. Account credentials and prior chat history are excluded. Without approved lesson passages, replies are general AI guidance. Sending a message saves the conversation only; it does not change your profile, goal or tasks.</p>
 </section>;
}
