'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import type {ChatMessage,Profile} from '@/lib/types';
import type {MentorResponse,StudentContext} from '@/lib/mentor-contract';
import {TopicLearning} from './topic-learning';
import Link from 'next/link';
import {startGuide} from '@/lib/guide-actions';
import {DishaAvatar} from './disha-avatar';
import {MentorMarkdown} from './mentor-markdown';
async function api(path:string,method='GET',body?:unknown){const r=await fetch(`/api/mentor${path}`,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error||'Please try again.');return d;}
type Memory={_id:string;topicId:string;text:string;source:string;updatedAt:string};
type Message=ChatMessage&{mentor?:MentorResponse};
const evidenceLabel={profile_self_report:'Profile · self-reported',confirmed_self_report:'Confirmed memory · self-reported',assessment:'Unvalidated topic-check evidence',completed_task:'Completed-task record'};
function MentorTurn({item,busy,decide,remember,choose,check,retry}:{item:Message;busy:boolean;decide:(id:string,v:unknown)=>void;remember:(v:unknown)=>void;choose:(choice:'refresher'|'continue',topicId?:string)=>void;check:()=>void;retry:()=>void}){
 const [editing,setEditing]=useState(false),[dismissed,setDismissed]=useState(false);
 const m=item.mentor;if(!m)return null;
 const proposal=m.proposal;
 return <div className="mentor-result">
  <small className="mentor-status">{m.sourceLabel==='Reviewed lesson'||m.passages.length>0?'Reviewed lesson':m.providerStatus==='local'?'Local guidance':m.providerStatus==='used'?'General AI guidance':'AI unavailable'}</small>
  {m.retryable&&m.passages.length>0&&<small>Reviewed lesson available; AI guidance temporarily unavailable.</small>}
  {m.uncertainty.filter(t=>/translated|insufficient|conflict/i.test(t)).map(t=><p className="mentor-warning" key={t}>{t}</p>)}
  {m.learning&&<p className="muted">{m.learning.title} · Step {m.learning.step+1}</p>}
  {m.retryable&&<button className="secondary" disabled={busy} onClick={retry}>Retry AI reply</button>}
  {m.labLanguage&&<Link className="text-button" href="/aprajita">Practise {m.labLanguage==='c'?'C':'Python'} in APRAJITA</Link>}
  {m.prerequisites.length>0&&<section><h3>Prerequisites to consider</h3>{m.prerequisiteSource&&<a href={m.prerequisiteSource.url} target="_blank" rel="noopener noreferrer">Source: {m.prerequisiteSource.title}</a>}<ul className="mentor-list">{m.prerequisites.map(p=><li key={p.topicId}><strong>{p.title}</strong><span className="pill">{p.status==='supported'?'Some recent evidence':p.status==='revisit'?'Worth revisiting':'Not yet checked'}</span><p>{p.reason}</p><p>{p.explanation}</p></li>)}</ul></section>}
  <details className="mentor-context"><summary>Sources &amp; context</summary><p>Saved with this reply; later profile edits do not rewrite it.</p>  {m.uncertainty.length>0&&<section><h4>Uncertainty</h4><ul>{m.uncertainty.map(t=><li key={t}>{t}</li>)}</ul></section>}
  <section><h4>Saved evidence at the time</h4>{m.evidence.length?<ul className="mentor-list">{m.evidence.map((e,i)=><li key={`${e.sourceRef}-${i}`}><strong>{evidenceLabel[e.source]}</strong><p>{e.text}</p><small>{e.topicId||'Profile context'} · {e.at?new Date(e.at).toLocaleDateString():'Date not recorded'}{e.version?` · Version ${e.version.slice(0,8)}`:''}</small></li>)}</ul>:<p>No relevant saved evidence was found.</p>}</section>
  {!!m.recentProgress?.length&&<section><h4>Recent progress at the time</h4><ul className="mentor-list">{m.recentProgress.map((p,i)=><li key={i}><strong>{p.title}</strong><p>{p.status==='done'?'Marked complete':p.status==='needs_help'?'Help requested':p.status==='irrelevant'?'No longer relevant':'To do'}{p.feeling?` · ${p.feeling.replaceAll('_',' ')}`:''}</p>{p.reflection&&<p>{p.reflection}</p>}<small>{p.at?new Date(p.at).toLocaleDateString():'Date not recorded'} · Activity does not establish mastery.</small></li>)}</ul></section>}
  {m.passages.length>0&&<section><h4>Sources</h4><ol>{m.passages.map(p=><li key={p.id}><a href={p.sourceUrl} target="_blank" rel="noopener noreferrer">{p.title} — {p.heading}</a><p>{p.text}</p><small>Version {p.version.slice(0,8)} · Reviewed {new Date(p.reviewedAt).toLocaleDateString()}</small></li>)}</ol></section>}
  {m.resources.length>0&&<div><h3>Reviewed resource links</h3><ul>{m.resources.map(r=><li key={r.id}><a href={r.url} target="_blank" rel="noopener noreferrer">{r.title} ↗</a></li>)}</ul><p>These links are resource metadata, not ingested lessons.</p></div>}
</details>
  {m.mode!=='conversation'&&!m.learning?.packVersion&&<><div className="topic-actions" aria-label="Choose how to continue"><button className="secondary" disabled={busy} onClick={check}>Quick topic check</button><button className="secondary" disabled={busy} onClick={()=>choose('refresher',m.topic?.id)}>Prerequisite refresher</button><button className="text-button" disabled={busy} onClick={()=>choose('continue',m.topic?.id)}>Continue to the topic</button></div>
  <section className="mentor-proposal"><h3>{proposal.title}</h3><p>{proposal.explanation}</p><p>{proposal.minutes} minutes · {proposal.notes}</p>
   {proposal.status==='pending'?editing?<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);decide(item._id,{decision:'edit',title:f.get('title'),notes:f.get('notes'),minutes:Number(f.get('minutes'))});setEditing(false);}}><label className="field"><span>Step</span><input name="title" defaultValue={proposal.title} required maxLength={150}/></label><label className="field"><span>Notes</span><textarea name="notes" defaultValue={proposal.notes} maxLength={2000}/></label><label className="field"><span>Minutes</span><input name="minutes" type="number" min={5} max={600} required defaultValue={proposal.minutes}/></label><div className="topic-actions"><button className="primary" disabled={busy}>Save edited step to my plan</button><button type="button" className="text-button" onClick={()=>setEditing(false)}>Cancel</button></div></form>:<div className="topic-actions"><button className="primary" disabled={busy} onClick={()=>decide(item._id,{decision:'accept'})}>Accept step</button><button className="secondary" disabled={busy} onClick={()=>setEditing(true)}>Edit first</button><button className="text-button" disabled={busy} onClick={()=>decide(item._id,{decision:'reject'})}>Not now</button></div>:<p role="status">{proposal.status==='accepted'?'Step saved to your plan.':'Suggestion dismissed. You can continue independently.'}</p>}
  </section></>}
  {m.memorySuggestion&&!dismissed&&<details><summary>Optional memory — confirm before saving</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);remember({messageRef:item._id,topicId:m.memorySuggestion!.topicId,text:f.get('text'),confirmed:true});}}><p>This is an interpretation of your message, not a confirmed fact. Edit it or leave it unsaved.</p><label className="field"><span>What would you like DISHA to remember?</span><textarea name="text" defaultValue={m.memorySuggestion.text} maxLength={300} required/></label><div className="topic-actions"><button className="secondary" disabled={busy}>Confirm and remember</button><button type="button" className="text-button" onClick={()=>setDismissed(true)}>Do not save</button></div></form></details>}
 </div>;
}
export function MentorWorkspace({active,signedIn,profile,messages,geminiConfigured,initialQuestion,draft,onDraft,onReload,onProfile,onSignIn}:{active:boolean;signedIn:boolean;profile:Profile;messages:ChatMessage[];geminiConfigured:boolean;initialQuestion?:string;draft:string;onDraft:(value:string)=>void;onReload:()=>Promise<void>;onProfile:()=>void;onSignIn:()=>void}){
 const message=draft,setMessage=onDraft;const language=(messages as Message[]).filter(m=>m.mentor?.language).at(-1)?.mentor?.language||'English';const [topicId,setTopic]=useState('');
 const [context,setContext]=useState<StudentContext|null>(null),[topics,setTopics]=useState<{id:string;title:string}[]>([]),[memories,setMemories]=useState<Memory[]>([]),[showMemory,setShowMemory]=useState(false),[editMemory,setEditMemory]=useState<string|null>(null);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[showCheck,setShowCheck]=useState(false);const [pending,setPending]=useState(''),[newReply,setNewReply]=useState(false),[retries,setRetries]=useState<Record<string,Message>>({});const [entranceIds,setEntranceIds]=useState<string[]>([]);const scroll=useRef<HTMLDivElement>(null),textarea=useRef<HTMLTextAreaElement>(null),nearBottom=useRef(true);const lock=useRef(false);const checkPanel=useRef<HTMLElement>(null);const contextGeneration=useRef(0);const alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;contextGeneration.current++;};},[]);
 useEffect(()=>{if(initialQuestion)setMessage(initialQuestion);},[initialQuestion]);
 useEffect(()=>{const el=textarea.current;if(el){el.style.height='auto';el.style.height=`${Math.min(el.scrollHeight,140)}px`;}},[message]);
 useEffect(()=>{if(nearBottom.current){scroll.current?.scrollTo({top:scroll.current.scrollHeight});setNewReply(false);}else setNewReply(true);},[messages,pending,retries,active]);
 useEffect(()=>{if(!active)return;const update=()=>{const v=window.visualViewport,height=v?.height||window.innerHeight;const top=Math.max(0,(scroll.current?.closest('main')?.getBoundingClientRect().top||0)-(v?.offsetTop||0));const nav=document.querySelector<HTMLElement>('.mobile-nav')?.getBoundingClientRect().height||0;document.documentElement.style.setProperty('--mentor-workspace-height',`${Math.max(160,height-top-nav)}px`);};update();window.addEventListener('resize',update);window.visualViewport?.addEventListener('resize',update);window.visualViewport?.addEventListener('scroll',update);return()=>{window.removeEventListener('resize',update);window.visualViewport?.removeEventListener('resize',update);window.visualViewport?.removeEventListener('scroll',update);document.documentElement.style.removeProperty('--mentor-workspace-height');};},[active]);
 useEffect(()=>{if(!active)setEntranceIds([]);},[active]);
 useEffect(()=>{if(showCheck)checkPanel.current?.focus();},[showCheck]);
 async function loadContext(){const generation=++contextGeneration.current;const r=await api(`/context?language=${encodeURIComponent(language)}`);if(!alive.current||generation!==contextGeneration.current)return;setContext(r.context);setMemories(r.memories);setTopics(r.topics);}
 useEffect(()=>{let cancelled=false;const generation=++contextGeneration.current;setContext(null);setMemories([]);setTopics([]);if(signedIn)api(`/context?language=${encodeURIComponent(language)}`).then(r=>{if(!cancelled&&generation===contextGeneration.current){setContext(r.context);setMemories(r.memories);setTopics(r.topics);}}).catch(e=>{if(!cancelled&&generation===contextGeneration.current)setError(e.message);});return()=>{cancelled=true;};},[signedIn,language,profile]);
 async function run(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){if(alive.current)setError((e as Error).message);}finally{if(alive.current){setBusy(false);setPending('');}lock.current=false;}}
 async function send(text:string,choice='consider',selected=topicId){if(!signedIn){onSignIn();return;}await run(async()=>{setPending(text);const result=await api('','POST',{message:text,choice,...(selected?{topicId:selected}:{})});if(!alive.current)return;if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches)setEntranceIds(ids=>[...ids,String(result.id)]);setMessage('');setPending('');await onReload();});}
 async function mutate(path:string,method:string,value?:unknown){await run(async()=>{await api(path,method,value);if(!alive.current)return;await Promise.all([onReload(),loadContext()]);setNotice('Saved.');});}
 async function retry(item:Message){await run(async()=>{const r=await api('','POST',{message:'Retry generation',retryRef:item._id});if(alive.current)setRetries(v=>({...v,[item._id]:{...item,content:r.answer,mentor:r.mentor}}));});}
 function submit(e:FormEvent){e.preventDefault();void send(message);}
 return <section hidden={!active} data-active={active} className="mentor-workspace" aria-label="DISHA chat workspace"><header className="mentor-header"><span className="disha-portrait"><DishaAvatar/></span><div><h1>DISHA</h1><small>Your learning mentor</small></div><button className="secondary" aria-expanded={showMemory} onClick={()=>setShowMemory(!showMemory)}>Memory</button><button className="text-button mentor-guide-button" onClick={()=>startGuide('disha')}>Guide</button><details className="mentor-menu"><summary aria-label="Conversation menu">•••</summary><div><button className="text-button" disabled={busy||!messages.length} onClick={()=>{if(confirm('Delete your saved conversation? Confirmed memories remain.')){setRetries({});setMessage('');void mutate('','DELETE');}}}>Clear conversation</button><details><summary>Privacy</summary><p>AI requests share your question, limited current profile and progress, and up to eight recent messages (6,000 characters) with Google. Credentials are excluded. Current profile wins over old replies. Messages are saved; tasks and memories need separate confirmation.</p></details></div></details></header>
  {error&&<p role="alert" className="inline-note error">{error}</p>}{notice&&<p role="status">{notice}</p>}
  {showMemory&&<section className="memory panel mentor-memory"><h2>What DISHA remembers</h2><p>{context?.education||'No saved education details yet.'}</p><p>{context?.goal||'No saved goal yet.'}</p><button className="text-button" onClick={onProfile}>Edit my profile</button><p>Profile entries and confirmed memories are self-reported. Task completion does not prove mastery. Forgetting removes the confirmed memory. Its text may still appear in recent conversation history until you clear the conversation.</p>
   {!memories.length&&<p>No extra mentor memories have been confirmed.</p>}<ul className="mentor-list">{memories.map(m=><li key={m._id}>{editMemory===m._id?<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate(`/memory/${m._id}`,'PATCH',{text:f.get('text'),confirmed:true});setEditMemory(null);}}><label className="field"><span>Edit memory about {m.topicId}</span><textarea name="text" defaultValue={m.text} maxLength={300} required/></label><button className="secondary" disabled={busy}>Confirm change</button><button type="button" className="text-button" onClick={()=>setEditMemory(null)}>Cancel</button></form>:<><p>{m.text}</p><small>{m.topicId} · {m.source.replaceAll('_',' ')} · {new Date(m.updatedAt).toLocaleDateString()}</small><div className="topic-actions"><button className="text-button" disabled={busy} onClick={()=>setEditMemory(m._id)}>Edit</button><button className="text-button" disabled={busy} onClick={()=>void mutate(`/memory/${m._id}`,'DELETE')}>Forget</button></div></>}</li>)}</ul>
   {signedIn&&<details><summary>Add a memory yourself</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate('/memory','POST',{topicId:f.get('topicId'),text:f.get('text'),confirmed:true});}}><label className="field"><span>Topic</span><select name="topicId" required><option value="general">Study preferences</option>{topics.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label className="field"><span>Your experience or preference</span><textarea name="text" required maxLength={300}/></label><button className="secondary" disabled={busy}>Confirm and remember</button></form></details>}
  </section>}
  <details className="mentor-learning-context"><summary>Learning context {messages.length>0&&(messages as Message[]).filter(m=>m.mentor?.learning).at(-1)?.mentor?.learning?.title&&<span className="pill">{(messages as Message[]).filter(m=>m.mentor?.learning).at(-1)?.mentor?.learning?.title}</span>}</summary><label className="field"><span>Optional topic</span><select value={topicId} onChange={e=>setTopic(e.target.value)}><option value="">Use the topic in my message</option>{topics.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label></details>
  <div ref={scroll} className="mentor-conversation" role="log" aria-label="Conversation" aria-live="polite" onScroll={e=>{const el=e.currentTarget;nearBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<80;if(nearBottom.current)setNewReply(false);}}>
   {messages.length?(messages as Message[]).map(saved=>{const m=retries[saved._id]||saved;return <article className={`mentor-bubble ${m.role}`} data-new={entranceIds.includes(m._id)||undefined} onAnimationEnd={event=>{if(event.target===event.currentTarget)setEntranceIds(ids=>ids.filter(id=>id!==m._id));}} key={m._id}><small>{m.role==='user'?'You':'DISHA'}{retries[saved._id]?' · Retry preview (saved reply unchanged)':''}</small><MentorMarkdown content={m.content}/>{m.role==='assistant'&&<MentorTurn item={m} busy={busy} decide={(id,v)=>void mutate(`/proposals/${id}`,'PATCH',v)} remember={v=>void mutate('/memory','POST',v)} choose={(choice,id)=>void send(choice==='continue'?'I want to continue to the topic.':'I would like a prerequisite refresher.',choice,id)} check={()=>setShowCheck(true)} retry={()=>void retry(saved)}/>}</article>;}):<div className="mentor-empty"><h2>What are you working on?</h2><p>Start small. Reviewed C, C++ and Python basics work without AI.</p><div className="topic-actions">{['Explain a topic','Help with code','Plan my next step'].map(text=><button key={text} className="secondary" onClick={()=>{setMessage(text==='Explain a topic'?'Teach Python basics':text);textarea.current?.focus();}}>{text}</button>)}</div></div>}
   {busy&&<>{pending&&<article className="mentor-bubble user"><MentorMarkdown content={pending}/></article>}<p className="mentor-typing" role="status"><span className="typing-dots" aria-hidden="true"><i/><i/><i/></span>DISHA is preparing your reply…</p></>}
  </div>
  {newReply&&<button className="mentor-new secondary" onClick={()=>{nearBottom.current=true;scroll.current?.scrollTo({top:scroll.current.scrollHeight});setNewReply(false);}}>New reply ↓</button>}
  <form data-guide-id="disha-composer" className="mentor-composer" onSubmit={submit}><textarea ref={textarea} rows={1} aria-label="Message DISHA" placeholder="Ask DISHA…" value={message} maxLength={2000} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing&&e.nativeEvent.keyCode!==229){e.preventDefault();if(message.trim()&&!busy)void send(message);}}}/><button className="primary" disabled={busy||!message.trim()}>{busy?'Sending…':signedIn?'Send':'Sign in'}</button><small>Enter to send · Shift+Enter for a new line</small></form>
  {showCheck&&<section className="panel" ref={checkPanel} tabIndex={-1}><h2>Available topic checks</h2><p>A check may not yet exist for the prerequisite you want. These checks are optional and unvalidated.</p><TopicLearning initialOpen hasGoal={!!profile.goal.trim()} onAccepted={onReload}/><button className="text-button" onClick={()=>setShowCheck(false)}>Close checks</button></section>}
 </section>;
}
