'use client';
import {useEffect,useRef,useState} from 'react';
import type {TopicAttempt,TopicQuestion,TopicSummary,ResourceFeeling} from '@/lib/topic-types';
async function request(path:string,method='GET',value?:unknown){const r=await fetch(`/api/topics${path}`,{method,headers:value?{'Content-Type':'application/json'}:undefined,body:value?JSON.stringify(value):undefined});const data=await r.json();if(!r.ok)throw new Error(data.error||'Please try again.');return data;}
export function TopicLearning({onAccepted,hasGoal,initialOpen=false}:{onAccepted:()=>Promise<void>;hasGoal:boolean;initialOpen?:boolean}){
 const [open,setOpen]=useState(initialOpen),[topics,setTopics]=useState<TopicSummary[]>([]),[history,setHistory]=useState<TopicAttempt[]>([]);
 const [stage,setStage]=useState<'subject'|'topic'|'language'|'time'|'offer'|'check'|'result'>('subject');
 const [subject,setSubject]=useState(''),[topicId,setTopicId]=useState(''),[language,setLanguage]=useState(''),[minutes,setMinutes]=useState(20);
 const [check,setCheck]=useState<{id:string;questions:TopicQuestion[]}|null>(null),[index,setIndex]=useState(0),[answers,setAnswers]=useState<Record<string,string>>({});
 const [result,setResult]=useState<TopicAttempt|null>(null),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState('');
 const heading=useRef<HTMLHeadingElement>(null),lock=useRef(false);
 const topic=topics.find(t=>t.id===topicId),question=check?.questions[index];
 async function run(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 async function reload(){const [t,h]=await Promise.all([request(''),request('/attempts')]);setTopics(t.topics);setHistory(h.attempts);setLoaded(true);}
 useEffect(()=>{if(open&&!loaded)void run(reload);},[open,loaded]); // Private state unmounts at sign-out.
 useEffect(()=>{if(open)heading.current?.focus();},[stage,index,open]);
 function reset(){setStage('subject');setResult(null);setCheck(null);setAnswers({});setIndex(0);setSubject('');setTopicId('');setLanguage('');setError('');}
 async function submit(skipped:boolean){await run(async()=>{const input=skipped?{topicId,language,minutes,skipped:true}:{topicId,language,minutes,skipped:false,assessmentId:check!.id,answers:check!.questions.map(q=>({questionId:q.id,answer:answers[q.id]}))};const r=await request('/attempts','POST',input);setResult(r.attempt);setStage('result');await reload();});}
 async function accept(resourceId:string){await run(async()=>{await request(`/attempts/${result!._id}`,'POST',{resourceId});const h=await request('/attempts');setHistory(h.attempts);setResult(h.attempts.find((a:TopicAttempt)=>a._id===result!._id)||result);await onAccepted();});}
 async function feedback(feeling:ResourceFeeling){await run(async()=>{await request(`/attempts/${result!._id}`,'PATCH',{feeling});const h=await request('/attempts');setHistory(h.attempts);setResult(h.attempts.find((a:TopicAttempt)=>a._id===result!._id)||result);});}
 const titles={subject:'What subject would you like to work on?',topic:'Which topic?',language:'Which resource language?',time:'How much time do you have for one session?',offer:'Would you like a short topic check?',check:question?.prompt||'Topic check',result:result?.topicTitle||'Your resource suggestions'};
 return <div className="topic-learning">
  <button className="text-button" aria-expanded={open} aria-controls="topic-flow" onClick={()=>setOpen(!open)}>{open?'Close topic suggestions':'Find a resource for a topic'}</button>
  {open&&<section id="topic-flow" className="topic-flow" aria-busy={busy}>
   <h3 ref={heading} tabIndex={-1}>{titles[stage]}</h3>
   {error&&<p className="inline-note error" role="alert">{error}</p>}
   {!loaded?<><p>Loading your available topics…</p>{!busy&&<button className="secondary" onClick={()=>void run(reload)}>Try again</button>}</>:
    !topics.length&&stage!=='result'?<p>No matching topics are available for your saved education details. Check your class, board and actual subjects, or programme and discipline, in your profile. This initial catalogue does not cover Class 12 or every programme.</p>:<>
    {stage==='subject'&&<label className="field"><span>Subject</span><select value={subject} onChange={e=>{setSubject(e.target.value);setTopicId('');}}><option value="">Choose a subject</option>{[...new Set(topics.map(t=>t.subject))].map(s=><option key={s}>{s}</option>)}</select></label>}
    {stage==='topic'&&<label className="field"><span>Topic</span><select value={topicId} onChange={e=>{setTopicId(e.target.value);setLanguage('');setCheck(null);setAnswers({});}}><option value="">Choose a topic</option>{topics.filter(t=>t.subject===subject).map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></label>}
    {stage==='language'&&<label className="field"><span>Resource language</span><select value={language} onChange={e=>setLanguage(e.target.value)}><option value="">Choose a language</option>{topic?.languages.map(l=><option key={l}>{l}</option>)}</select></label>}
    {stage==='time'&&<label className="field"><span>Minutes available</span><input type="number" min={5} max={120} step={1} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label>}
    {['subject','topic','language','time'].includes(stage)&&<div className="topic-actions"><button className="primary" disabled={busy||(stage==='subject'&&!subject)||(stage==='topic'&&!topicId)||(stage==='language'&&!language)||(stage==='time'&&(!Number.isInteger(minutes)||minutes<5||minutes>120))} onClick={()=>setStage(stage==='subject'?'topic':stage==='topic'?'language':stage==='language'?'time':'offer')}>Continue</button>{stage!=='subject'&&<button className="text-button" onClick={()=>setStage(stage==='topic'?'subject':stage==='language'?'topic':'language')}>Back</button>}</div>}
    {stage==='offer'&&<><p>This optional check suggests concepts to revisit. It is not a validated aptitude assessment or a judgment about you. Questions are in English.</p><div className="topic-actions">{topic?.assessmentId&&<button className="primary" disabled={busy} onClick={()=>void run(async()=>{const c=await request(`/checks/${topic.assessmentId}`);setCheck(c);setAnswers({});setIndex(0);setStage('check');})}>Try the topic check</button>}<button className="secondary" disabled={busy} onClick={()=>void submit(true)}>Skip and find resources</button><button className="text-button" onClick={()=>setStage('time')}>Back</button></div></>}
    {stage==='check'&&question&&<><p>Question {index+1} of {check!.questions.length}</p><progress value={index+1} max={check!.questions.length} aria-label={`Question ${index+1} of ${check!.questions.length}`}/><fieldset className="topic-options"><legend className="sr-only">{question.prompt}</legend>{question.options.map(o=><label key={o.id}><input type="radio" name={question.id} value={o.id} checked={answers[question.id]===o.id} onChange={()=>setAnswers({...answers,[question.id]:o.id})}/><span>{o.label}</span></label>)}</fieldset><div className="topic-actions"><button className="primary" disabled={busy||!answers[question.id]} onClick={()=>index+1<check!.questions.length?setIndex(index+1):void submit(false)}>{index+1<check!.questions.length?'Next question':'See suggestions'}</button>{index>0&&<button className="text-button" disabled={busy} onClick={()=>setIndex(index-1)}>Back</button>}<button className="text-button" disabled={busy} onClick={()=>void submit(true)}>Skip check</button></div></>}
    {stage==='result'&&result&&<>
     <p>{result.skipped?'You skipped the check. No understanding has been inferred.':'These answers offer a starting point for this topic, not an overall score or ability label.'}</p>
     {result.results.length>0&&<details><summary>Concepts and answer explanations</summary><ul className="topic-concepts">{result.results.map(r=><li key={r.questionId}><strong>{r.objective}</strong><p>{r.result==='understood'?'Your answer matched the supplied key.':r.result==='not_sure'?'You chose Not sure. You could start here.':'This answer suggests revisiting this concept.'}</p><p>{r.explanation} Supplied answer: {r.answer}.</p></li>)}</ul></details>}
     {!result.recommendations.length&&<p>No suitable resources match this check and your preferences yet.</p>}
     <div className="topic-recommendations">{result.recommendations.map(r=><article key={r.resourceId}><h4>{r.title}</h4><p>{r.provider} · {r.language}</p><dl><dt>Full resource effort</dt><dd>{r.effort}</dd><dt>Access</dt><dd>{r.access}</dd><dt>Prerequisites</dt><dd>{r.prerequisites}</dd></dl><p>{r.approach}</p><details><summary>Why this resource?</summary><ul>{r.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul><p>{r.limitations}</p></details><div className="topic-actions"><a className="text-button" href={r.url} target="_blank" rel="noopener noreferrer">Open resource ↗</a>{!result.acceptance&&<button className="primary" disabled={busy||!hasGoal} onClick={()=>void accept(r.resourceId)}>Add {r.minutes}-minute session to my goal</button>}{result.acceptance?.resourceId===r.resourceId&&<p role="status">Saved to your plan · {result.acceptance.goalTitle}</p>}</div></article>)}</div>
     {!hasGoal&&!result.acceptance&&<p>Save a personal goal in your profile before adding a resource to your plan.</p>}
     <p className="muted">Opening a link does not complete the task. You decide when it is complete.</p>
     {result.acceptance&&<fieldset className="topic-feedback"><legend>After trying it, how did this resource feel?</legend><div className="topic-actions">{([['too_easy','Too easy'],['about_right','About right'],['too_difficult','Too difficult']] as const).map(([feeling,label])=><button key={feeling} className="secondary" aria-pressed={result.feedback?.feeling===feeling} disabled={busy} onClick={()=>void feedback(feeling)}>{label}</button>)}</div>{result.feedback&&<p role="status">Saved. Your next suggestions for this topic will use this feedback.</p>}</fieldset>}
     <button className="text-button" disabled={busy} onClick={reset}>Choose a topic again</button>
    </>}
   </>}
   {loaded&&stage==='subject'&&history.length>0&&<div className="topic-history"><h4>Your recent topic checks</h4><ul>{history.map(a=><li key={a._id}><button className="text-button" onClick={()=>{setResult(a);setStage('result');}}>{a.topicTitle} · {a.skipped?'Skipped check':'Check saved'}{a.acceptance?' · Resource chosen':''}</button><time dateTime={a.createdAt}>{new Date(a.createdAt).toLocaleDateString()}</time></li>)}</ul></div>}
  </section>}
 </div>;
}
